### ISSUE TITLE
Fragezeichen für Vor- und Nachnamen weglassen

### ISSUE THREAD

**Issue by flash1293** [Yannic92/shoppingList#1]
![2016-01-02](https://cloud.githubusercontent.com/assets/1508364/12075472/25c289aa-b182-11e5-9e06-b20a14cf7b01.png)

Fragezeichen für die Namen sind unnötig - am besten einfach weglassen, sieht am besten aus.

**Comment by Yannic92** [comment]
Closed with f450bd8bf1cf3a2b6b9950828f71dbe1838ed0ac
