### ISSUE TITLE
Sinnlose Fehlermeldung bei Löschen des eigenen Users von Einkaufsliste

### ISSUE THREAD

**Issue by flash1293** [Yannic92/shoppingList#2]
![2016-01-02 1](https://cloud.githubusercontent.com/assets/1508364/12075474/4682f1b6-b182-11e5-9a3e-17f254b2d7d1.png)

Am besten Mülleimer gar nicht einblenden oder sinnvolle Fehlermeldung

**Comment by Yannic92** [comment]
Mülleimer nicht einblenden erscheint sinnvoll. Aber wieso ist diese Fehlermeldung nicht hilfreich? Sie hat dir doch gesagt was falsch war oder nicht?

**Comment by flash1293** [comment]
Ne - wieso bin ich nicht berechtigt, an meiner eigenen Liste was zu ändern? Verstehe ich als Nutzer nicht

**Comment by Yannic92** [comment]
Ah verstehe .. was damit gemeint ist, ist dass du keine Liste erstellen kannst an der du hinterher nicht berechtigt wärst .. aber ja ich sehe das Problem. Werde einfach den Löschenbutton nicht bieten für den eigenen Nutzer
