### ISSUE TITLE
Anbindung an das CoffeeNet

### ISSUE THREAD

**Issue by derTobsch** [Yannic92/shoppingList#21]
Es wäre schön, wenn die ShoppingList an das CoffeeNet angebunden wäre, sodass man es mit SSO verwenden könnte.

**Comment by derTobsch** [comment]
uuuuuuuuuuuuuuuuuund? :)

**Comment by Yannic92** [comment]
Wäre eine coole Idee, aber dazu müsste der Auth-Server noch eine Funktion bekommen, um neue Nutzer zu erstellen. Was wären denn andere Anwendungen die du damit verknüpfen willst? :)

**Comment by derTobsch** [comment]
man müsste den ldap abstrahieren beim auth server und könnte dann ein einfaches user management hinpacken...

**Comment by derTobsch** [comment]
@Yannic92 ich frage ich gerade warum wir das brauchen und nicht einfach ein ldap dahin stellen? :) Dann kann man einfach user im ldap anlegen und gut ist.

**Comment by Yannic92** [comment]
Es wäre schon schön, wenn man sich als user direkt registrieren könnte, ohne etwas über ein ldap zu wissen, das irgendwo rumgeistert :>

**Comment by derTobsch** [comment]
k, nun weiss ich was du meintest. Hatte es falsch verstanden...glaube ich :) du solltest wieder neben mir sitzen....dann ist das einfacher mit der Kommunikation.

Man könnte zweierlei dinge tun.

* Auth Server mit einer Maske zum Registrieren von Usern versehen
* Separaten Service bereitstellen welcher user in den Ldap speichert

Bounded Context?

**Comment by Yannic92** [comment]
Da das CoffeeNet bisher sehr auf microservices setzt, wäre ich für die zweite Option. Es könnte ja optional bei der Login-Maske n Link zur registrierung auftauchen, falls ein Service verfügbar ist, der irgendwie "usermanagement" oder sowas heißt. Eventuell auch über die Metadaten abbilden. Müsste man sich noch Gedanken machen.

**Comment by derTobsch** [comment]
Genau das gleiche Konzept hatte ich auch im Kopf. Hast du Lust das Projekt mit mir zu starten? :) Wie hast du Zeit usw? dann können wir einfach mal ein hangout machen

**Comment by Yannic92** [comment]
Da Abschlussarbeit ist etwas knapp. Aber ich könnt so 2-3h jeden Samstag zum gemeinsam (via Hangout) coden anbieten? rest halt so wenns mal reinpasst

**Comment by derTobsch** [comment]
wenn du bock hast bindest du es einfach mal an. Das mit den Usern gehen wir dann einfach parallel an :)
