### ISSUE TITLE
Android 5.* Such-Icon in Tastatur

### ISSUE THREAD

**Issue by flash1293** [Yannic92/shoppingList#5]
Die Tastatur für Hinzufügen von List-Items hat ein Such-Icon unten rechts (eig. sollte da ein Pfeil sein oder so)

**Comment by Yannic92** [comment]
Wird erst mal nicht behoben. Ich warte mal ab ob sich bei einem dieser issues in angular material noch etwas tut:
- https://github.com/angular/material/issues/5040
- https://github.com/angular/material/issues/6517

Falls sich da nicht bald was ergibt schaue ich nach ner eigenen Lösung für autocompletion

**Comment by Yannic92** [comment]
fixed by #e72743a8f76a0c15cafede0ee7363bf628b6c12d

**Comment by Yannic92** [comment]
solved by e72743a8f76a0c15cafede0ee7363bf628b6c12d
