### ISSUE TITLE
401-Fehler wenn nicht eingeloggt

### ISSUE THREAD

**Issue by flash1293** [Yannic92/shoppingList#7]
Wenn man die Seite in nicht eingeloggtem Zustand aufruft, wird zweimal eine URL angefordert, die einen 401-Fehler wirft: GET https://wg.yannic-klem.de/sLUsers/current 401 (Unauthorized)

**Comment by Yannic92** [comment]
tatsächlich ist das mein test, OB bereits eine authentifizierung besteht. Ich bin nicht komplett RESTful unterwegs ;) Nutze die Session noch zur authentifizierung. 
Oder stört es dich, dass es 2 statt eigentlich nur einer notwendigen Request sind?

**Comment by flash1293** [comment]
Aso, kann man so machen :-) ich hab das bei unserer Projektarbeit so
gemacht, dass es einen Endpoint /tokenValidity gibt, der liefert immer 200
und ein json-dokument zurück, ob man eingeloggt ist. Keine Ahnung ob das
besser ist.
Dass es zweimal passiert ist natürlich nicht so hübsch.

Yannic92 notifications@github.com schrieb am Mi., 6. Jan. 2016 19:09:

**Comment by Yannic92** [comment]
solved in 3b282a88b448ce8b7e2d68bb7133938fa4ea09ec
